// ===========================================================
// FARM2HOME — product catalogue
// Shared between products.html (grid) and product.html (detail page)
// ===========================================================

const PRODUCTS = [
  {
    id: "heirloom-tomatoes",
    name: "Heirloom Tomatoes",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 60,
    unit: "kg",
    farm: "Green Valley Farm",
    distance: "4km away",
    badge: "Picked 6am",
    img: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=700&q=80",
    tags: ["No pesticides", "Vine-ripened"],
    desc: "Knobby, deep-red heirlooms grown without pesticides and picked the morning they ship. Sweeter and juicier than the uniform tomatoes you'll find in a supermarket — best eaten within 4 days of delivery."
  },
  {
    id: "garden-carrots",
    name: "Garden Carrots",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 45,
    unit: "kg",
    farm: "Sunrise Organics",
    distance: "7km away",
    badge: "Picked 7am",
    img: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&w=700&q=80",
    tags: ["Organic", "Soil-grown"],
    desc: "Crisp, earthy carrots pulled straight from the soil this morning. Naturally sweet with none of the bitterness that comes from weeks in cold storage."
  },
  {
    id: "bunched-spinach",
    name: "Bunched Spinach",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 30,
    unit: "bunch",
    farm: "Riverbend Fields",
    distance: "3km away",
    badge: "Picked 5am",
    img: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=700&q=80",
    tags: ["Zero pesticide", "Hand-picked"],
    desc: "Tender, dark-green leaves hand-picked at dawn. Keeps its snap for days when stored in a damp cloth in the fridge."
  },
  {
    id: "sweet-corn",
    name: "Sweet Corn",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 20,
    unit: "pc",
    farm: "Golden Acre Farm",
    distance: "9km away",
    badge: "Picked 6am",
    img: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=700&q=80",
    tags: ["In season", "Non-GMO"],
    desc: "Plump, milky kernels at their peak sweetness. Corn starts converting sugar to starch the moment it's picked, so we ship same-day for maximum sweetness."
  },
  {
    id: "bell-peppers",
    name: "Bell Peppers",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 70,
    unit: "kg",
    farm: "Green Valley Farm",
    distance: "4km away",
    badge: "Picked 6am",
    img: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=700&q=80",
    tags: ["No pesticides", "Crunchy"],
    desc: "A mixed trio of red, yellow and green peppers, thick-walled and crisp. Great raw in salads or charred on a tawa."
  },
  {
    id: "purple-brinjal",
    name: "Purple Brinjal",
    category: "veg",
    categoryLabel: "Vegetables",
    price: 40,
    unit: "kg",
    farm: "Sunrise Organics",
    distance: "7km away",
    badge: "Picked 7am",
    img: "https://images.unsplash.com/photo-1528826006993-9a1ff5b6e0ff?auto=format&fit=crop&w=700&q=80",
    tags: ["Organic", "Firm skin"],
    desc: "Glossy, firm brinjal with almost no seeds — perfect for baingan bharta or a quick stir fry."
  },
  {
    id: "alphonso-mangoes",
    name: "Alphonso Mangoes",
    category: "fruit",
    categoryLabel: "Fruits",
    price: 150,
    unit: "kg",
    farm: "Konkan Orchard",
    distance: "12km away",
    badge: "Picked today",
    img: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=700&q=80",
    tags: ["Tree-ripened", "Limited season"],
    desc: "The king of mangoes — tree-ripened, fibreless and deeply fragrant. Ships in small batches while the season lasts."
  },
  {
    id: "strawberries",
    name: "Strawberries",
    category: "fruit",
    categoryLabel: "Fruits",
    price: 90,
    unit: "box",
    farm: "Hillcrest Berries",
    distance: "15km away",
    badge: "Dawn harvest",
    img: "https://images.unsplash.com/photo-1518635017480-d9d5323d0cae?auto=format&fit=crop&w=700&q=80",
    tags: ["Hill-grown", "Hand-picked"],
    desc: "Deep-red hill berries picked at first light and packed in ventilated boxes so they arrive firm, not bruised."
  },
  {
    id: "bananas",
    name: "Bananas",
    category: "fruit",
    categoryLabel: "Fruits",
    price: 50,
    unit: "dozen",
    farm: "Golden Acre Farm",
    distance: "9km away",
    badge: "Picked today",
    img: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=700&q=80",
    tags: ["Naturally ripened", "No carbide"],
    desc: "Naturally ripened on the plant — no carbide, no gas rooms. A little more spotty than store bananas, a lot more flavour."
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    category: "fruit",
    categoryLabel: "Fruits",
    price: 120,
    unit: "kg",
    farm: "Riverbend Fields",
    distance: "3km away",
    badge: "Picked yesterday",
    img: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?auto=format&fit=crop&w=700&q=80",
    tags: ["Hand-selected", "Deep red arils"],
    desc: "Hand-selected for weight and colour — a sure sign of juicy, deep-red arils inside."
  },
  {
    id: "brown-rice",
    name: "Brown Rice",
    category: "grain",
    categoryLabel: "Grains & Pulses",
    price: 80,
    unit: "kg",
    farm: "Paddy Co-op",
    distance: "20km away",
    badge: "Freshly milled",
    img: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&q=80",
    tags: ["Stone-milled", "Single origin"],
    desc: "Stone-milled in small batches from a single co-operative, keeping the bran intact for extra fibre and a nuttier bite."
  },
  {
    id: "toor-dal",
    name: "Toor Dal",
    category: "grain",
    categoryLabel: "Grains & Pulses",
    price: 110,
    unit: "kg",
    farm: "Paddy Co-op",
    distance: "20km away",
    badge: "Freshly milled",
    img: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=700&q=80",
    tags: ["Unpolished", "No additives"],
    desc: "Unpolished split pigeon peas with no added colour or preservatives — cooks down soft and full of flavour."
  },
  {
    id: "farm-paneer",
    name: "Farm Paneer",
    category: "dairy",
    categoryLabel: "Dairy",
    price: 90,
    unit: "200g",
    farm: "Green Meadow Dairy",
    distance: "6km away",
    badge: "Made today",
    img: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=700&q=80",
    tags: ["Made same-day", "No preservatives"],
    desc: "Pressed fresh every morning from that day's milk — soft, mild and free of preservatives. Best used within 3 days."
  },
  {
    id: "a2-cow-milk",
    name: "A2 Cow Milk",
    category: "dairy",
    categoryLabel: "Dairy",
    price: 65,
    unit: "L",
    farm: "Green Meadow Dairy",
    distance: "6km away",
    badge: "Morning milk",
    img: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=700&q=80",
    tags: ["A2 breed", "Unhomogenized"],
    desc: "Unhomogenized A2 milk from grass-fed indigenous cows, chilled and delivered within hours of the morning milking."
  },
  {
    id: "fresh-coriander",
    name: "Fresh Coriander",
    category: "herb",
    categoryLabel: "Herbs",
    price: 15,
    unit: "bunch",
    farm: "Riverbend Fields",
    distance: "3km away",
    badge: "Picked 6am",
    img: "https://images.unsplash.com/photo-1615485291234-c8ac9d0e6b1c?auto=format&fit=crop&w=700&q=80",
    tags: ["Root-on", "Aromatic"],
    desc: "Sold root-on to stay fresher longer — just trim and store in water like a bunch of flowers."
  },
  {
    id: "mint-leaves",
    name: "Mint Leaves",
    category: "herb",
    categoryLabel: "Herbs",
    price: 12,
    unit: "bunch",
    farm: "Riverbend Fields",
    distance: "3km away",
    badge: "Picked 6am",
    img: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?auto=format&fit=crop&w=700&q=80",
    tags: ["Aromatic", "Hand-picked"],
    desc: "Fragrant pudina picked in small hand-tied bunches — ideal for chutneys, teas and cooling summer drinks."
  }
];

// Secondary gallery images reused across every product (farm + crate context shots)
const GALLERY_EXTRAS = [
  "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=700&q=80",
  "https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=700&q=80"
];
